[book]
authors = ["Pete Stenger"]
language = "en"
multilingual = false
src = "src"
title = "Fall CTF 2024 Guide"

[output.html]
mathjax-support = true
default-theme = "navy"
site-url = "/guide-2024/"
preferred-dark-theme = "navy"
git-repository-url  = "https://github.com/sigpwny/websites/tree/main/fallctf.com"
edit-url-template = "https://github.com/rust-lang/mdBook/edit/main/fallctf.com/guide-2024/{path}"
additional-css = ["theme/css/custom.css"]
[output.html.code.hidelines]
python = "~"