[book]
authors = ["Pete Stenger"]
language = "en"
multilingual = false
src = "src"
title = "Fall CTF 2024 Guide"

[output.html]
mathjax-support = true
site-url = "/mdBook/"

[output.html.code.hidelines]
python = "~"