name: Build mdbook
description: Builds an mdbook site
inputs:
  book-directory:
    description: Output directory of built mdbook site (from working directory)
    required: true
    type: array
    
runs:
  using: composite
  steps:
  - uses: actions/checkout@master
  - name: Install Rust
    shell: bash
    run: |
      rustup set profile minimal
      rustup toolchain install stable
      rustup default stable
  - name: Install latest mdbook
    shell: bash
    run: |
      tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
      url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
      mkdir bin
      curl -sSL $url | tar -xz --directory=bin
      echo "$(pwd)/bin" >> $GITHUB_PATH
  - name: Build site
    shell: bash
    run: cd ${{ inputs.book-directory }} && mdbook build