name: Deploy Astro Site

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
      build_dir:
        required: true
        type: string
env:
  CI: true
  CI_WORKING_DIR: ${{ github.event.inputs.working_dir }}
  CI_BUILD_DIR: ${{ github.event.inputs.build_dir }}
jobs:
  deploy-astro:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Restore cached node modules and build artifacts
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.npm
            ${{ env.CI_WORKING_DIR }}/node_modules
            ${{ env.CI_WORKING_DIR }}/.astro
            ${{ env.CI_WORKING_DIR }}/${{ env.CI_BUILD_DIR }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: (On cache miss) List the state of node modules
        continue-on-error: true
        run: npm list
        working-directory: ${{ env.CI_WORKING_DIR }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: (On cache miss) Install node modules
        continue-on-error: true
        run: npm ci
        working-directory: ${{ env.CI_WORKING_DIR }}

      - name: Build site
        run: npm run build
        working-directory: ${{ env.CI_WORKING_DIR }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          workingDirectory: ${{ env.CI_WORKING_DIR }}
          directory: ${{ env.CI_BUILD_DIR }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
